controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\HomeController.php

items:
    path: /items
    controller: App\Controller\ItemsController.php

additem:
    path: /additem
    controller: App\Controller\AdditemController.php

cart:
    path: /cart
    controller: App\Controller\CartController.php
