controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


home:
    path: /
    controller: App\Controller\HomeController::index

items:
    path: /items
    controller: App\Controller\ItemsController::index

additem:
    path: /additem
    controller: App\Controller\AdditemController::additem

cart:
    path: /cart
    controller: App\Controller\CartController::index
